### ISSUE TITLE
More useful output?

### ISSUE THREAD

**Issue by chalmersgit** [tdsuper/SphericalSuperpixels#1]
Hi, I tested your spherical segmentation, and it works nicely. However, it's an executable, so I cannot modify it or get access to the segmented pixels. The current output is an outline of the segmentation, which is nice for visualisation, but not useful for my actual task (I do not have a reliable way of extracting each segment). A more useful output would be one where each segment has a unique colour ID. That way I can easily use the output as a mask to extract the segments.

Would it be possible to modify the executable to output such an image? Or alternatively provide the source code?

**Comment by tdsuper** [comment]
@chalmersgit Actually, along with the visual segmentation result, the program also outputs a text file, which gives the labels of the pixels.

**Comment by chalmersgit** [comment]
Ah right, completely missed it, thanks! Are the labels in row order?

Maybe updating the readme about the output would help. For example: "Outputs a text file containing the labels for each pixel (in row order) as well as a visualisation of the segmentation."

Thanks again.

**Comment by tdsuper** [comment]
@chalmersgit Yes, the labels are in row order. And I have updated the ReadMe file. Thanks for your suggestion.
