### ISSUE TITLE
Distance types?

### ISSUE THREAD

**Issue by chalmersgit** [tdsuper/SphericalSuperpixels#2]
What are the possible options for the distance type argument -t? I cannot see it specified in the readme.

From your paper, I see there is  Cos-SphSLIC and Avg-SphSLIC. Any others? And how do we specify them? "-t Avg-SphSLIC"? Or does it expect some kind of integer ID? "-t 0"?

**Comment by tdsuper** [comment]
@chalmersgit Hi, I give the parameter details in the updated ReadMe. If there are some thing that I have not described clearly, please let me know. Thanks!

**Comment by chalmersgit** [comment]
Thanks, it's a lot clearer now.
